#!/usr/bin/env bash

# Traverse to the path of this script
# https://stackoverflow.com/a/24112741
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" || exit ; pwd -P )
cd "$parent_path" || exit

# Alias elab to execute the elab tool of experiment_utils with root
# sudo -E is required to have sudo working inside the nix chroot
sudo -E $(which nix) run .#elab -- "${@}"