name: latex

on: [push, pull_request]

jobs:
  latex:
    runs-on: self-hosted
    container:
      image: ghcr.io/xu-cheng/texlive-debian
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Build pdf
      run: |
        cd thesis
        make all
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: PDF
    #     path: thesis/main.pdf
    #     overwrite: 'true'