name: pylint

on: [push, pull_request]


jobs:
  pylint:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Emit pylint warnings on all .py files
      run: |
        find -type f -name '*.py' | xargs -I{} pylint {}