name: shellcheck

on: [push, pull_request]


jobs:
  shellcheck:
    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: |
        sudo apt install shellcheck
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Emit shellcheck warning and errors on all .sh files
      run: |
        find -type f -name '*.sh' | xargs -I{} shellcheck -S warning {}